version: 0.2

phases:
  build:
    commands:
      - echo "Building the application..."
      - mvn clean package
  post_build:
    commands:
      - echo "Build completed successfully..."
artifacts:
  files:
    - target/demo.jar
  discard-paths: yes